### ISSUE TITLE
Questions about comparison of TC, BC, TC w.o. imitation learning

### ISSUE THREAD

**Issue by Moreland-cas** [ShengranHu/Thought-Cloning#3]
Halo, great work!
In fig3 of the main paper, BC eventually catch up with the TC, but why is TC without imitation loss perform much worse, and don't even catch up with the BC in the end? 
They both lack of the supervision from thoughts, so the performance gap come from the architecture difference?

**Comment by ShengranHu** [comment]
Hello. Thanks for your question! We believe it is correct that the performance gap between BC and TC without imitating thought comes from the architectural difference. Also, our hypothesis is that because TC without imitating thought has an extra part of the thought generator that remains untrained, the training of the model is hindered. For completeness, we also do an ablation where we let BC have the same parameter as TC but retain BC's architecture (Appendix B).

**Comment by Moreland-cas** [comment]
Okay, thanks for your quick reply :)
